# Generated by Django 5.1.2 on 2025-11-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_options_remove_deal_amount_and_more'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-created_at'], 'verbose_name': 'Доход', 'verbose_name_plural': 'Доходы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(blank=True, help_text='Дата расхода', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(help_text='Тип расхода', max_length=120),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, help_text='Примечание'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(help_text='Платёж', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finances.payment'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма (в рублях)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.TextField(blank=True, help_text='Примечание'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment',
            field=models.ForeignKey(help_text='Платёж', on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finances.payment'),
        ),
        migrations.AlterField(
            model_name='income',
            name='received_at',
            field=models.DateField(blank=True, help_text='Дата получения', null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, help_text='Источник', max_length=120),
        ),
        migrations.AlterField(
            model_name='payment',
            name='actual_date',
            field=models.DateField(blank=True, help_text='Фактическая дата', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма (в рублях)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='Сделка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='deals.deal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, help_text='Описание', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Запланированная дата', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('partial', 'Частичный'), ('paid', 'Оплачен')], default='planned', help_text='Статус', max_length=20),
        ),
    ]
