# Generated by Django 5.1.2 on 2025-11-11 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_activitylog'),
        ('finances', '0003_financialtransaction'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='Полис', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policies.policy'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='Сделка (денормализованное поле для производительности)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='deals.deal'),
        ),
    ]
