# Generated by Django 5.1.2 on 2026-03-18 23:06

from django.db import migrations, models


def backfill_financial_record_type(apps, schema_editor):
    FinancialRecord = apps.get_model("finances", "FinancialRecord")
    FinancialRecord.objects.filter(amount__lt=0).update(record_type="expense")
    FinancialRecord.objects.filter(amount__gte=0).update(record_type="income")


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0009_fix_paid_statement_record_dates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="statement",
            new_name="finances_st_stateme_b85b04_idx",
            old_name="finances_st_statement_8a37a1_idx",
        ),
        migrations.RenameIndex(
            model_name="statement",
            new_name="finances_st_status_e60ee6_idx",
            old_name="finances_st_status_ef2a8b_idx",
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="record_type",
            field=models.CharField(
                choices=[("income", "Доход"), ("expense", "Расход")],
                default="income",
                help_text="Тип записи",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_financial_record_type,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="statement",
            name="paid_at",
            field=models.DateField(
                blank=True,
                help_text="Дата выплаты ведомости. Если заполнено — ведомость считается выплаченной.",
                null=True,
            ),
        ),
    ]
