# Generated by Django 5.1.2 on 2026-07-10 11:07

import apps.common.indexes
from django.db import migrations, models

BALANCE_INDEX = models.Index(
    condition=models.Q(("date__isnull", False), ("deleted_at__isnull", True)),
    fields=["payment"],
    include=("amount",),
    name="finrec_balance_active_idx",
)
DESCRIPTION_INDEX = apps.common.indexes.PostgresTrigramIndex(
    "description", name="finrec_desc_trgm_idx"
)
SOURCE_INDEX = apps.common.indexes.PostgresTrigramIndex(
    "source", name="finrec_source_trgm_idx"
)
NOTE_INDEX = apps.common.indexes.PostgresTrigramIndex(
    "note", name="finrec_note_trgm_idx"
)
PAYMENT_DESCRIPTION_INDEX = apps.common.indexes.PostgresTrigramIndex(
    "description", name="payment_desc_trgm_idx"
)
FINANCIAL_RECORD_INDEXES = (
    BALANCE_INDEX,
    DESCRIPTION_INDEX,
    SOURCE_INDEX,
    NOTE_INDEX,
)


def ensure_index(schema_editor, model, index):
    if schema_editor.connection.vendor != "postgresql":
        schema_editor.add_index(model, index)
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT pg_index.indisvalid
            FROM pg_class
            JOIN pg_index ON pg_index.indexrelid = pg_class.oid
            JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
            WHERE pg_class.relname = %s
              AND pg_namespace.nspname = current_schema()
            """,
            [index.name],
        )
        row = cursor.fetchone()
    if row and row[0]:
        return
    if row:
        schema_editor.execute(
            f"DROP INDEX CONCURRENTLY IF EXISTS {schema_editor.quote_name(index.name)}"
        )
    schema_editor.add_index(model, index, concurrently=True)


def drop_index(schema_editor, model, index):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            f"DROP INDEX CONCURRENTLY IF EXISTS {schema_editor.quote_name(index.name)}"
        )
        return
    schema_editor.remove_index(model, index)


def create_indexes(apps, schema_editor):
    financial_record = apps.get_model("finances", "FinancialRecord")
    payment = apps.get_model("finances", "Payment")
    for index in FINANCIAL_RECORD_INDEXES:
        ensure_index(schema_editor, financial_record, index)
    ensure_index(schema_editor, payment, PAYMENT_DESCRIPTION_INDEX)


def remove_indexes(apps, schema_editor):
    financial_record = apps.get_model("finances", "FinancialRecord")
    payment = apps.get_model("finances", "Payment")
    drop_index(schema_editor, payment, PAYMENT_DESCRIPTION_INDEX)
    for index in reversed(FINANCIAL_RECORD_INDEXES):
        drop_index(schema_editor, financial_record, index)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("deals", "0037_deal_deal_title_trgm_idx"),
        ("finances", "0012_finance_search_indexes"),
        ("policies", "0021_policy_policy_number_trgm_idx"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_indexes, remove_indexes)],
            state_operations=[
                migrations.AddIndex(model_name="financialrecord", index=BALANCE_INDEX),
                migrations.AddIndex(
                    model_name="financialrecord", index=DESCRIPTION_INDEX
                ),
                migrations.AddIndex(model_name="financialrecord", index=SOURCE_INDEX),
                migrations.AddIndex(model_name="financialrecord", index=NOTE_INDEX),
                migrations.AddIndex(
                    model_name="payment", index=PAYMENT_DESCRIPTION_INDEX
                ),
            ],
        )
    ]
