# Generated by Django 5.1.2 on 2026-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0013_financialrecord_finrec_balance_active_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_balance",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                help_text="Денормализованная сумма проведённых финансовых записей",
                max_digits=12,
            ),
        ),
    ]
