# Generated by Django 5.1.2 on 2026-08-08 20:12

from django.db import migrations
from django.db.models import Sum


def backfill_paid_balance(apps, schema_editor):
    Payment = apps.get_model("finances", "Payment")
    FinancialRecord = apps.get_model("finances", "FinancialRecord")
    totals = (
        FinancialRecord.objects.filter(deleted_at__isnull=True, date__isnull=False)
        .values("payment_id")
        .annotate(total=Sum("amount"))
    )
    for row in totals.iterator(chunk_size=1000):
        Payment.objects.filter(pk=row["payment_id"]).update(
            paid_balance=row["total"] or 0
        )


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0014_payment_paid_balance"),
    ]

    operations = [
        migrations.RunPython(backfill_paid_balance, migrations.RunPython.noop)
    ]
