# Generated by Django 5.1.2 on 2026-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0015_backfill_payment_paid_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="deletion_snapshot",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
