"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import importlib
import os
from datetime import timedelta
from pathlib import Path

from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

importlib.import_module("config.admin")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default=None)
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set to a non-empty value.")
if SECRET_KEY == "unsafe-dev-key":
    raise ImproperlyConfigured(
        "The unsafe-dev-key placeholder must be replaced in production."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default="False").lower() in ("true", "1", "yes")

raw_allowed_hosts = config("ALLOWED_HOSTS", default="")
ALLOWED_HOSTS = [host.strip() for host in raw_allowed_hosts.split(",") if host.strip()]
if any(host == "*" for host in ALLOWED_HOSTS):
    raise ImproperlyConfigured(
        "Use specific ALLOWED_HOSTS entries instead of '*' for hardening."
    )
if not DEBUG:
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS must be populated when DEBUG is False."
        )
else:
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


def _bool_env(var: str, default: str) -> bool:
    return config(var, default=default).strip().lower() in ("true", "1", "yes")


CSRF_TRUSTED_ORIGINS = [
    origin for origin in config("CSRF_TRUSTED_ORIGINS", default="").split(",") if origin
]
if DEBUG and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = ["http://localhost:8000"]


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "django_filters",
    "import_export",
    "apps.common",
    "apps.users",
    "apps.clients",
    "apps.deals",
    "apps.tasks",
    "apps.documents",
    "apps.notifications",
    "apps.finances",
    "apps.notes",
    "apps.chat",
    "apps.policies",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DJANGO_DB_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DJANGO_DB_NAME", default=str(BASE_DIR / "db.sqlite3")),
        "USER": config("DJANGO_DB_USER", default=""),
        "PASSWORD": config("DJANGO_DB_PASSWORD", default=""),
        "HOST": config("DJANGO_DB_HOST", default=""),
        "PORT": config("DJANGO_DB_PORT", default=""),
        "ATOMIC_REQUESTS": False,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE = config(
    "GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE", default=""
)
GOOGLE_DRIVE_ROOT_FOLDER_ID = config("GOOGLE_DRIVE_ROOT_FOLDER_ID", default="")
GOOGLE_DRIVE_DOCUMENT_LIBRARY_FOLDER_ID = config(
    "GOOGLE_DRIVE_DOCUMENT_LIBRARY_FOLDER_ID", default=""
)

OPENROUTER_API_KEY = config("OPENROUTER_API_KEY", default="")
OPENROUTER_BASE_URL = config("OPENROUTER_BASE_URL", default="")
OPENROUTER_MODEL = config("OPENROUTER_MODEL", default="")
AI_POLICY_PROMPT = config("AI_POLICY_PROMPT", default="")
AI_DOCUMENT_PROMPT = config("AI_DOCUMENT_PROMPT", default="")

OPEN_NOTEBOOK_API_URL = config("OPEN_NOTEBOOK_API_URL", default="")
OPEN_NOTEBOOK_PASSWORD = config("OPEN_NOTEBOOK_PASSWORD", default="")
OPEN_NOTEBOOK_TIMEOUT_SECONDS = float(
    config("OPEN_NOTEBOOK_TIMEOUT_SECONDS", default="300")
)
OPEN_NOTEBOOK_EMBED_ON_UPLOAD = _bool_env("OPEN_NOTEBOOK_EMBED_ON_UPLOAD", "true")
OPEN_NOTEBOOK_MEDIA_ROOT = config("OPEN_NOTEBOOK_MEDIA_ROOT", default=str(MEDIA_ROOT))
OPEN_NOTEBOOK_CONTEXT_LEVEL = config(
    "OPEN_NOTEBOOK_CONTEXT_LEVEL", default="full content"
)

TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN", default="")
TELEGRAM_BOT_USERNAME = config("TELEGRAM_BOT_USERNAME", default="")
TELEGRAM_POLL_TIMEOUT = int(config("TELEGRAM_POLL_TIMEOUT", default="30"))
TELEGRAM_REMINDER_INTERVAL = int(config("TELEGRAM_REMINDER_INTERVAL", default="300"))
TELEGRAM_LINK_CODE_TTL_MINUTES = int(
    config("TELEGRAM_LINK_CODE_TTL_MINUTES", default="10")
)
CRM_PUBLIC_URL = config("CRM_PUBLIC_URL", default="")
DEAL_PIN_LIMIT = int(config("DEAL_PIN_LIMIT", default="5"))

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TTL_MIN", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TTL_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": SECRET_KEY,
    "ALGORITHM": "HS256",
}

CORS_ALLOW_ALL_ORIGINS = _bool_env("CORS_ALLOW_ALL_ORIGINS", "False")
if CORS_ALLOW_ALL_ORIGINS:
    raise ImproperlyConfigured(
        "CORS_ALLOW_ALL_ORIGINS=True is not allowed; configure CORS_ALLOWED_ORIGINS."
    )

CORS_ALLOWED_ORIGINS = [
    origin for origin in config("CORS_ALLOWED_ORIGINS", default="").split(",") if origin
]
if not CORS_ALLOWED_ORIGINS:
    if DEBUG:
        CORS_ALLOWED_ORIGINS = ["http://localhost:3000"]
    else:
        raise ImproperlyConfigured(
            "CORS_ALLOWED_ORIGINS must be set when DEBUG is False."
        )

CORS_EXPOSE_HEADERS = ["Content-Disposition"]

# Control whether Django emits the Cross-Origin-Opener-Policy header so that
# it can be disabled when serving over unsecured HTTP origins (e.g. local
# dev machines). Set SECURE_CROSS_ORIGIN_OPENER_POLICY in production to enforce.
raw_coop_policy = config("SECURE_CROSS_ORIGIN_OPENER_POLICY", default="")
SECURE_CROSS_ORIGIN_OPENER_POLICY = raw_coop_policy or None

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
