# Generated by Django 5.1.2 on 2026-01-05 16:20

import apps.notifications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_notification_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_enabled', models.BooleanField(default=False, help_text='Telegram enabled')),
                ('notify_tasks', models.BooleanField(default=True, help_text='New tasks')),
                ('notify_deal_events', models.BooleanField(default=True, help_text='Deal events')),
                ('notify_deal_expected_close', models.BooleanField(default=True, help_text='Deal expected close reminders')),
                ('notify_payment_due', models.BooleanField(default=True, help_text='Payment due reminders')),
                ('remind_days', models.JSONField(default=apps.notifications.models._default_remind_days, help_text='Reminder days before deadline')),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification settings',
                'verbose_name_plural': 'Notification settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, help_text='Telegram chat id', null=True, unique=True)),
                ('linked_at', models.DateTimeField(blank=True, help_text='Linked at', null=True)),
                ('link_code', models.CharField(blank=True, help_text='One-time link code for /start', max_length=64)),
                ('link_code_expires_at', models.DateTimeField(blank=True, help_text='Link code expiry', null=True)),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram profile',
                'verbose_name_plural': 'Telegram profiles',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Notification type', max_length=120)),
                ('object_type', models.CharField(blank=True, help_text='Object type', max_length=120)),
                ('object_id', models.CharField(blank=True, help_text='Object id', max_length=120)),
                ('trigger_date', models.DateField(help_text='Trigger date')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Sent at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification delivery',
                'verbose_name_plural': 'Notification deliveries',
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'object_type', 'object_id', 'trigger_date'), name='notifications_unique_delivery')],
            },
        ),
    ]
