# Generated by Django 5.1.2 on 2026-01-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationsettings_telegramprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="notify_policy_expiry",
            field=models.BooleanField(
                default=True, help_text="Policy expiry reminders"
            ),
        ),
    ]
