# Generated by Django 5.1.2 on 2026-02-21 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_email_optional'),
        ('deals', '0027_dealtimetick'),
        ('notifications', '0005_notificationsettings_next_contact_lead_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat id')),
                ('message_id', models.BigIntegerField(help_text='Telegram message id')),
                ('update_id', models.BigIntegerField(help_text='Telegram update id')),
                ('text', models.TextField(blank=True, help_text='Extracted source text')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw Telegram payload')),
                ('status', models.CharField(choices=[('received', 'Received'), ('waiting_decision', 'Waiting decision'), ('linked_existing', 'Linked existing deal'), ('created_new_deal', 'Created new deal'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('failed', 'Failed')], default='received', help_text='Processing status', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When message processing was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_deal', models.ForeignKey(blank=True, help_text='Linked deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_inbound_messages', to='deals.deal')),
                ('user', models.ForeignKey(help_text='CRM user', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_inbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram inbound message',
                'verbose_name_plural': 'Telegram inbound messages',
            },
        ),
        migrations.CreateModel(
            name='TelegramDealRoutingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('linked_existing', 'Linked existing deal'), ('created_new_deal', 'Created new deal'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', help_text='Session state', max_length=32)),
                ('expires_at', models.DateTimeField(help_text='Session expiration timestamp')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Parsed data from telegram message')),
                ('candidate_deal_ids', models.JSONField(blank=True, default=list, help_text='Ordered candidate deals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_client', models.ForeignKey(blank=True, help_text='Client created during routing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_routing_created_sessions', to='clients.client')),
                ('created_deal', models.ForeignKey(blank=True, help_text='Deal created during routing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_routing_created_sessions', to='deals.deal')),
                ('selected_deal', models.ForeignKey(blank=True, help_text='Deal picked by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_routing_selected_sessions', to='deals.deal')),
                ('user', models.ForeignKey(help_text='CRM user', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_deal_routing_sessions', to=settings.AUTH_USER_MODEL)),
                ('inbound_message', models.OneToOneField(help_text='Inbound message being routed', on_delete=django.db.models.deletion.CASCADE, related_name='routing_session', to='notifications.telegraminboundmessage')),
            ],
            options={
                'verbose_name': 'Telegram deal routing session',
                'verbose_name_plural': 'Telegram deal routing sessions',
            },
        ),
        migrations.AddIndex(
            model_name='telegraminboundmessage',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_dc7269_idx'),
        ),
        migrations.AddIndex(
            model_name='telegraminboundmessage',
            index=models.Index(fields=['processed_at'], name='notificatio_process_04a584_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegraminboundmessage',
            constraint=models.UniqueConstraint(fields=('chat_id', 'message_id'), name='notifications_unique_tg_chat_message'),
        ),
        migrations.AddIndex(
            model_name='telegramdealroutingsession',
            index=models.Index(fields=['user', 'state', 'expires_at'], name='notif_tg_route_idx'),
        ),
    ]
