# Generated by Django 5.1.2 on 2026-02-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_telegraminboundmessage_telegramdealroutingsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramdealroutingsession',
            name='inbound_message',
        ),
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='aggregated_attachments',
            field=models.JSONField(blank=True, default=list, help_text='Merged attachments from batch'),
        ),
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='aggregated_text',
            field=models.TextField(blank=True, default='', help_text='Merged text/caption from batch'),
        ),
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='batch_message_ids',
            field=models.JSONField(blank=True, default=list, help_text='Telegram message ids in this batch'),
        ),
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='batch_payloads',
            field=models.JSONField(blank=True, default=list, help_text='Batch source payloads'),
        ),
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='batch_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='Batch finalize timeout in seconds'),
        ),
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='decision_prompt_sent_at',
            field=models.DateTimeField(blank=True, help_text='When decision prompt was sent', null=True),
        ),
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Last message timestamp in batch', null=True),
        ),
        migrations.AddField(
            model_name='telegraminboundmessage',
            name='routing_session',
            field=models.ForeignKey(blank=True, help_text='Batch routing session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='notifications.telegramdealroutingsession'),
        ),
        migrations.AlterField(
            model_name='telegramdealroutingsession',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending (legacy)'), ('collecting', 'Collecting'), ('ready', 'Ready'), ('linked_existing', 'Linked existing deal'), ('created_new_deal', 'Created new deal'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('failed', 'Failed')], default='collecting', help_text='Session state', max_length=32),
        ),
    ]
