# Generated by Django 5.1.2 on 2026-02-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_telegramdealroutingsession_inbound_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramdealroutingsession',
            name='status_message_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram message id for collecting status updates', null=True),
        ),
    ]
