# Generated by Django 5.1.2 on 2026-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_telegramdealroutingsession_status_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="sber_login",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Personal Sber Insurance login",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="sber_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Personal Sber Insurance password",
                max_length=255,
            ),
        ),
    ]
