# Generated by Django 5.1.2 on 2026-09-23 11:14

import apps.ai_assistant.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to=apps.ai_assistant.models.document_upload_path)),
                ('status', models.CharField(db_index=True, default='queued', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('chunks_count', models.PositiveIntegerField(default=0)),
                ('insurer', models.CharField(blank=True, max_length=255)),
                ('insurance_kind', models.CharField(blank=True, max_length=255)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=255)),
                ('effective_from', models.CharField(blank=True, max_length=32)),
                ('effective_to', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Новый чат', max_length=255)),
                ('provider', models.CharField(default='polza', max_length=32)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('scope', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField(blank=True)),
                ('citations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_rub', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('request_status', models.CharField(blank=True, max_length=32)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('location', models.JSONField(default=dict)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_assistant.aidocument')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ai_assistan_search__f9f9f2_gin')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='ai_chunk_document_index_unique')],
            },
        ),
        migrations.CreateModel(
            name='AiRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_request_id', models.CharField(max_length=128)),
                ('status', models.CharField(db_index=True, default='queued', max_length=32)),
                ('found_chunks', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(max_length=255)),
                ('scope', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('worker_id', models.CharField(blank=True, max_length=64)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_run', to='ai_assistant.aimessage')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_assistant.aiconversation')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_run', to='ai_assistant.aimessage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'client_request_id'), name='ai_run_idempotency_unique'), models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'searching', 'generating'])), fields=('conversation',), name='ai_run_one_active_per_chat')],
            },
        ),
    ]
