# Generated by Django 5.1.2 on 2026-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.AddField(
            model_name='aimessage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
