# Generated by Django 5.1.2 on 2025-11-11 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('role', 'Роль'), ('permission', 'Право'), ('user_role', 'Роль пользователя'), ('role_permission', 'Право роли'), ('client', 'Клиент'), ('deal', 'Сделка'), ('task', 'Задача'), ('document', 'Документ'), ('payment', 'Платёж'), ('policy', 'Полис'), ('note', 'Заметка'), ('financial_record', 'Финансовая запись'), ('notification', 'Уведомление'), ('user', 'Пользователь')], help_text='Тип изменяемого объекта', max_length=50)),
                ('object_id', models.CharField(help_text='ID изменяемого объекта', max_length=255)),
                ('object_name', models.CharField(blank=True, help_text='Название объекта для удобства', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('assign', 'Назначение'), ('revoke', 'Отзыв')], help_text='Тип действия', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Подробное описание произошедшего изменения')),
                ('old_value', models.JSONField(blank=True, help_text='Старое значение (для update)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Новое значение (для update)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Пользователь, совершивший действие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='users_audit_object__f792c7_idx'), models.Index(fields=['actor', '-created_at'], name='users_audit_actor_i_fea760_idx'), models.Index(fields=['action', '-created_at'], name='users_audit_action_c40010_idx')],
            },
        ),
    ]
