# Generated by Django 5.1.2 on 2026-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('merge', 'Слияние'), ('delete', 'Удаление'), ('restore', 'Восстановление'), ('assign', 'Назначение'), ('revoke', 'Отзыв')], help_text='Тип действия', max_length=50),
        ),
    ]
