# Generated by Django 5.1.2 on 2026-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Создание"),
                    ("update", "Редактирование"),
                    ("merge", "Слияние"),
                    ("delete", "Удаление"),
                    ("restore", "Восстановление"),
                    ("assign", "Назначение"),
                    ("revoke", "Отзыв"),
                    ("reopen", "Возврат в черновик"),
                ],
                help_text="Тип действия",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("role", "Роль"),
                    ("permission", "Право"),
                    ("user_role", "Роль пользователя"),
                    ("role_permission", "Право роли"),
                    ("client", "Клиент"),
                    ("deal", "Сделка"),
                    ("task", "Задача"),
                    ("document", "Документ"),
                    ("payment", "Платёж"),
                    ("policy", "Полис"),
                    ("note", "Заметка"),
                    ("financial_record", "Финансовая запись"),
                    ("statement", "Финансовая ведомость"),
                    ("notification", "Уведомление"),
                    ("user", "Пользователь"),
                ],
                help_text="Тип изменяемого объекта",
                max_length=50,
            ),
        ),
    ]
