# Generated by Django 5.1.2 on 2026-09-26 11:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0016_client_birth_place_client_is_current_and_more"),
        ("deals", "0043_alter_quote_sum_insured"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mortgage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(max_length=255)),
                ("agreement_number", models.CharField(blank=True, max_length=255)),
                ("agreement_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("property_type", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("cadastral_number", models.CharField(blank=True, max_length=100)),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "construction_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deals.bank",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgages",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MortgageBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("as_of_date", models.DateField()),
                (
                    "mortgage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="insurance_requests.mortgage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InsuranceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("unlimited_drivers", models.BooleanField(default=False)),
                ("targets", models.JSONField(default=list)),
                ("deductibles", models.JSONField(blank=True, default=list)),
                ("official_dealer", models.BooleanField(blank=True, null=True)),
                (
                    "vehicle_value_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Фиксированная"),
                            ("maximum", "Максимальная"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "vehicle_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "mortgage_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("mortgage_amount_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "borrower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrower_requests",
                        to="clients.client",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_requests",
                        to="deals.deal",
                    ),
                ),
                (
                    "drivers",
                    models.ManyToManyField(
                        blank=True, related_name="driver_requests", to="clients.client"
                    ),
                ),
                (
                    "insurance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deals.insurancetype",
                    ),
                ),
                (
                    "insured_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insured_requests",
                        to="clients.client",
                    ),
                ),
                (
                    "mortgage_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deals.bank",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_requests",
                        to="clients.client",
                    ),
                ),
                (
                    "policyholder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policyholder_requests",
                        to="clients.client",
                    ),
                ),
                (
                    "mortgage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="insurance_requests.mortgage",
                    ),
                ),
                (
                    "mortgage_balance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="insurance_requests.mortgagebalance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("record_id", models.UUIDField()),
                ("action", models.CharField(max_length=20)),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "insurance_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="insurance_requests.insurancerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="RequestVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "deductible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает расчёта"),
                            ("quoted", "Предложения получены"),
                            ("declined", "Отказ"),
                            ("failed", "Не удалось рассчитать"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deals.insurancecompany",
                    ),
                ),
                (
                    "insurance_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="insurance_requests.insurancerequest",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="insurance_requests.platform",
                    ),
                ),
                (
                    "request_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="insurance_requests.requestversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(max_length=255)),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("plate", models.CharField(blank=True, max_length=30)),
                ("has_no_plate", models.BooleanField(default=False)),
                (
                    "power_hp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("mileage_date", models.DateField(blank=True, null=True)),
                ("key_count", models.PositiveSmallIntegerField(default=2)),
                ("notes", models.TextField(blank=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="insurancerequest",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="insurance_requests.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="VehicleRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("series", models.CharField(blank=True, max_length=30)),
                ("number", models.CharField(blank=True, max_length=50)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="insurance_requests.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleTitle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("series", models.CharField(blank=True, max_length=30)),
                ("number", models.CharField(blank=True, max_length=50)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("pts", "ПТС"), ("epts", "ЭПТС")],
                        default="pts",
                        max_length=4,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="insurance_requests.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientPassport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("series", models.CharField(blank=True, max_length=30)),
                ("number", models.CharField(blank=True, max_length=50)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("issued_by", models.CharField(blank=True, max_length=500)),
                ("department_code", models.CharField(blank=True, max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clients.client"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True), ("is_current", True)
                        ),
                        fields=("client",),
                        name="clientpassport_current_client",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DealParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal_participations",
                        to="clients.client",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("deal", "client"),
                        name="unique_live_deal_participant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("series", models.CharField(blank=True, max_length=30)),
                ("number", models.CharField(blank=True, max_length=50)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("country", models.CharField(default="РФ", max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("experience_start", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clients.client"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True), ("is_current", True)
                        ),
                        fields=("client",),
                        name="driverlicense_current_client",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="requestversion",
            constraint=models.UniqueConstraint(
                fields=("insurance_request", "number"), name="request_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="insurancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mortgage__isnull", True), ("vehicle__isnull", False)),
                    models.Q(("mortgage__isnull", False), ("vehicle__isnull", True)),
                    _connector="OR",
                ),
                name="request_exactly_one_object",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_current", True)),
                fields=("vehicle",),
                name="vehicleregistration_current_vehicle",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicletitle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_current", True)),
                fields=("vehicle",),
                name="vehicletitle_current_vehicle",
            ),
        ),
    ]
