# Generated by Django 5.1.2 on 2026-09-27 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0044_quote_insurance_request_quote_request_variant_and_more'),
        ('insurance_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasingCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='ownership_type',
            field=models.CharField(choices=[('unknown', 'Не указан'), ('owned', 'Без кредита и лизинга'), ('credit', 'Кредит'), ('leasing', 'Лизинг')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='vehicle_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_requests', to='deals.bank'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='leasing_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance_requests.leasingcompany'),
        ),
    ]
