# Generated by Django 5.1.2 on 2025-11-15 17:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


def populate_insurance_refs(apps, schema_editor):
    Policy = apps.get_model("policies", "Policy")
    InsuranceCompany = apps.get_model("deals", "InsuranceCompany")
    InsuranceType = apps.get_model("deals", "InsuranceType")

    company_cache: dict[str, uuid.UUID] = {}
    type_cache: dict[str, uuid.UUID] = {}
    default_company = "Не указано"
    default_type = "Не указано"

    for policy in Policy.objects.all().iterator():
        company_key = (getattr(policy, "insurance_company_text", "") or "").strip() or default_company
        company_id = company_cache.get(company_key)
        if company_id is None:
            company = InsuranceCompany.objects.get_or_create(name=company_key)[0]
            company_id = company.id
            company_cache[company_key] = company_id
        policy.insurance_company_temp = company_id

        type_key = (getattr(policy, "insurance_type_text", "") or "").strip() or default_type
        type_id = type_cache.get(type_key)
        if type_id is None:
            insurance_type = InsuranceType.objects.get_or_create(name=type_key)[0]
            type_id = insurance_type.id
            type_cache[type_key] = type_id
        policy.insurance_type_temp = type_id

        policy.save(update_fields=["insurance_company_temp", "insurance_type_temp"])


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0010_add_insurance_references"),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
            },
        ),
        migrations.RenameIndex(
            model_name="policy",
            new_name="policies_po_insuran_980ad6_idx",
            old_name="policies_po_insuran_a16d23_idx",
        ),
        migrations.RemoveField(model_name="policy", name="amount"),
        migrations.AddField(
            model_name="policy",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Vehicle make",
                max_length=255,
                verbose_name="Brand",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="is_vehicle",
            field=models.BooleanField(
                default=False, help_text="True when the policy is for a vehicle"
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="model",
            field=models.CharField(
                blank=True,
                help_text="Vehicle model",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.RenameField(
            model_name="policy",
            old_name="insurance_company",
            new_name="insurance_company_text",
        ),
        migrations.RenameField(
            model_name="policy",
            old_name="insurance_type",
            new_name="insurance_type_text",
        ),
        migrations.AddField(
            model_name="policy",
            name="insurance_company_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="policies",
                to="deals.InsuranceCompany",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="insurance_type_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="policies",
                to="deals.InsuranceType",
            ),
        ),
        migrations.RunPython(
            populate_insurance_refs,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(model_name="policy", name="insurance_company_text"),
        migrations.RemoveField(model_name="policy", name="insurance_type_text"),
        migrations.RenameField(
            model_name="policy",
            old_name="insurance_company_temp",
            new_name="insurance_company",
        ),
        migrations.RenameField(
            model_name="policy",
            old_name="insurance_type_temp",
            new_name="insurance_type",
        ),
        migrations.AlterField(
            model_name="policy",
            name="deal",
            field=models.ForeignKey(
                help_text="Deal",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="deals.deal",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Policy end date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="insurance_company",
            field=models.ForeignKey(
                help_text="Insurance company",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="deals.insurancecompany",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="insurance_type",
            field=models.ForeignKey(
                help_text="Insurance type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="deals.insurancetype",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="number",
            field=models.CharField(
                help_text="Policy number", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Policy start date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                default="active",
                help_text="Status (active, expired, canceled etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="Vehicle VIN (17 characters)",
                max_length=17,
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["insurance_type"], name="policies_po_insuran_f8c74f_idx"
            ),
        ),
    ]
