# Generated by Django 5.1.2 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


def populate_policy_client(apps, schema_editor):
    Policy = apps.get_model('policies', 'Policy')
    for policy in Policy.objects.filter(client__isnull=True).select_related('deal'):
        deal = getattr(policy, 'deal', None)
        if not deal:
            continue
        client_id = getattr(deal, 'client_id', None)
        if client_id is None:
            continue
        policy.client_id = client_id
        policy.save(update_fields=['client'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_name_alter_client_phone'),
        ('deals', '0011_alter_insurancecompany_description_and_more'),
        ('policies', '0003_policy_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['client'], name='policies_po_client__7a77dc_idx'),
        ),
        migrations.RunPython(populate_policy_client, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client'),
        ),
    ]
