# Generated by Django 5.1.2 on 2025-11-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_name_alter_client_phone'),
        ('policies', '0004_policy_client_policy_policies_po_client__7a77dc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client'),
        ),
    ]
