# Generated by Django 5.1.2 on 2025-11-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_alter_quote_insurance_company'),
        ('policies', '0006_policy_drive_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='insurance_company',
            field=models.ForeignKey(help_text='Insurance company', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='deals.insurancecompany'),
        ),
    ]
