# Generated by Django 5.1.2 on 2025-11-17 12:45

import django.db.models.deletion
from django.db import migrations, models


def move_channel_data(apps, schema_editor):
    SalesChannel = apps.get_model("deals", "SalesChannel")
    Deal = apps.get_model("deals", "Deal")
    Policy = apps.get_model("policies", "Policy")

    channel_map = {}

    def to_channel(name: str | None):
        if not name:
            return None
        trimmed = name.strip()
        if not trimmed:
            return None
        key = trimmed.casefold()
        channel = channel_map.get(key)
        if channel:
            return channel
        channel = SalesChannel.objects.create(name=trimmed)
        channel_map[key] = channel
        return channel

    for deal in Deal.objects.all():
        channel = to_channel(getattr(deal, "channel", None))
        if channel:
            Deal.objects.filter(pk=deal.pk).update(sales_channel=channel)

    for policy in Policy.objects.select_related("deal"):
        deal_channel = getattr(policy.deal, "sales_channel", None)
        if deal_channel:
            Policy.objects.filter(pk=policy.pk).update(sales_channel=deal_channel)


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0007_alter_policy_insurance_company"),
        ("deals", "0016_sales_channel_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="sales_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Канал продаж",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="deals.saleschannel",
            ),
        ),
        migrations.RunPython(move_channel_data, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["sales_channel"],
                name="policies_po_sales_c_51cd4d_idx",
            ),
        ),
    ]
