# Generated by Django 5.1.2 on 2025-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_email_optional'),
        ('deals', '0022_alter_quote_insurance_company'),
        ('policies', '0010_alter_policy_insurance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='number',
            field=models.CharField(help_text='Policy number', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('number',), name='policies_unique_active_number'),
        ),
    ]
