# Generated by Django 5.1.2 on 2026-03-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_email_optional'),
        ('policies', '0015_sync_client_from_insured_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Policy note'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insured_client',
            field=models.ForeignKey(blank=True, help_text='(Legacy) Insured client; kept for backward compatibility.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insured_policies', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', help_text='Status (active, inactive, expired, canceled).', max_length=50),
        ),
    ]
