# Generated by Django 5.1.2 on 2026-03-06 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0016_policy_note_alter_policy_insured_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyIssuanceExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('sber', 'Sber')], default='sber', max_length=32)),
                ('product', models.CharField(choices=[('osago_auto', 'OSAGO auto')], default='osago_auto', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_manual', 'Waiting manual'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=32)),
                ('step', models.CharField(blank=True, default='', max_length=128)),
                ('manual_step_reason', models.TextField(blank=True, default='')),
                ('manual_step_instructions', models.TextField(blank=True, default='')),
                ('external_policy_number', models.CharField(blank=True, default='', max_length=128)),
                ('last_error', models.TextField(blank=True, default='')),
                ('log', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('runtime_state', models.JSONField(blank=True, default=dict)),
                ('resume_token', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuance_executions', to='policies.policy')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_issuance_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy', '-created_at'], name='policies_po_policy__27c43e_idx'), models.Index(fields=['status', '-updated_at'], name='policies_po_status_669c19_idx')],
            },
        ),
    ]
