# Generated by Django 5.1.2 on 2026-04-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0017_policyissuanceexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='renewed_by',
            field=models.ForeignKey(blank=True, help_text='Policy that renews this policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_policies', to='policies.policy'),
        ),
    ]
