# Generated by Django 5.1.2 on 2026-05-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_policy_renewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='deductible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Франшиза', max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='gap',
            field=models.BooleanField(blank=True, default=None, help_text='Риск GAP (да/нет)', null=True, verbose_name='GAP'),
        ),
        migrations.AddField(
            model_name='policy',
            name='official_dealer',
            field=models.BooleanField(blank=True, default=None, help_text='Официальный дилер (да/нет)', null=True, verbose_name='Официальный дилер'),
        ),
    ]
