# Generated by Django 5.1.2 on 2026-05-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0019_policy_deductible_policy_gap_policy_official_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='renewed_by',
        ),
        migrations.AddField(
            model_name='policy',
            name='is_renewed',
            field=models.BooleanField(default=False, help_text='True when the policy has been renewed.'),
        ),
    ]
