# Generated by Django 5.1.2 on 2026-07-10 11:07

import apps.common.indexes
from django.db import migrations

INDEX = apps.common.indexes.PostgresTrigramIndex(
    "number", name="policy_number_trgm_idx"
)


def create_index(apps, schema_editor):
    model = apps.get_model("policies", "Policy")
    if schema_editor.connection.vendor != "postgresql":
        schema_editor.add_index(model, INDEX)
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT pg_index.indisvalid FROM pg_class "
            "JOIN pg_index ON pg_index.indexrelid = pg_class.oid "
            "JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace "
            "WHERE pg_class.relname = %s AND pg_namespace.nspname = current_schema()",
            [INDEX.name],
        )
        row = cursor.fetchone()
    if row and row[0]:
        return
    if row:
        schema_editor.execute(
            f"DROP INDEX CONCURRENTLY IF EXISTS {schema_editor.quote_name(INDEX.name)}"
        )
    schema_editor.add_index(model, INDEX, concurrently=True)


def remove_index(apps, schema_editor):
    model = apps.get_model("policies", "Policy")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            f"DROP INDEX CONCURRENTLY IF EXISTS {schema_editor.quote_name(INDEX.name)}"
        )
        return
    schema_editor.remove_index(model, INDEX)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("clients", "0013_client_client_name_trgm_idx"),
        ("deals", "0037_deal_deal_title_trgm_idx"),
        ("policies", "0020_remove_policy_renewed_by_policy_is_renewed"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_index, remove_index)],
            state_operations=[migrations.AddIndex(model_name="policy", index=INDEX)],
        )
    ]
