# Generated by Django 5.1.2 on 2026-09-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_client_referred_by'),
        ('deals', '0042_bank'),
        ('policies', '0021_policy_policy_number_trgm_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='loan_agreement_number',
            field=models.CharField(blank=True, default='', help_text='Номер кредитного договора по ипотечному полису', max_length=255),
        ),
        migrations.AddField(
            model_name='policy',
            name='mortgage_bank',
            field=models.ForeignKey(blank=True, help_text='Банк по ипотечному полису', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_policies', to='deals.bank'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['mortgage_bank'], name='policies_po_mortgag_404542_idx'),
        ),
    ]
