# Generated by Django 5.1.2 on 2026-09-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_requests", "0001_initial"),
        ("policies", "0022_policy_loan_agreement_number_policy_mortgage_bank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="insurance_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="insurance_requests.insurancerequest",
            ),
        ),
    ]
