# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_completion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Комментарий при завершении задачи",
            ),
        ),
    ]
