# Generated by Django 5.1.2 on 2025-11-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_client_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Client email address", max_length=254
            ),
        ),
    ]
