# Generated by Django 5.1.2 on 2025-12-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Client email address",
                max_length=254,
                null=True,
            ),
        ),
    ]
