# Generated by Django 5.1.2 on 2026-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_counterparty',
            field=models.BooleanField(default=False, help_text='Клиент является контрагентом'),
        ),
    ]
