# Generated by Django 5.1.2 on 2026-05-06 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_is_counterparty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMergeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_client_id', models.UUIDField(db_index=True)),
                ('source_client_ids', models.JSONField(default=list)),
                ('include_deleted', models.BooleanField(default=True)),
                ('preview_snapshot_id', models.CharField(blank=True, default='', max_length=255)),
                ('field_overrides', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('moving_drive', 'Moving Drive'), ('ready_to_finalize', 'Ready to finalize'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='moving_drive', max_length=32)),
                ('drive_items', models.JSONField(blank=True, default=list)),
                ('moved_items', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('retryable', models.BooleanField(default=False)),
                ('failed_item', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_merge_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='clients_cli_request_11233d_idx'), models.Index(fields=['status', '-updated_at'], name='clients_cli_status_e05d76_idx')],
            },
        ),
    ]
