# Generated by Django 5.1.2 on 2026-05-11 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientmergesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSimilarityExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_similarity_exclusions', to=settings.AUTH_USER_MODEL)),
                ('first_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_exclusions_as_first', to='clients.client')),
                ('second_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_exclusions_as_second', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['first_client', 'second_client'], name='clients_cli_first_c_adcd4b_idx'), models.Index(fields=['second_client', 'first_client'], name='clients_cli_second__58231f_idx')],
                'constraints': [models.UniqueConstraint(fields=('first_client', 'second_client'), name='unique_client_similarity_exclusion_pair'), models.CheckConstraint(condition=models.Q(('first_client', models.F('second_client')), _negated=True), name='client_similarity_exclusion_distinct_clients')],
            },
        ),
    ]
