# Generated by Django 5.1.2 on 2026-08-08 16:04

import apps.common.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_client_client_name_trgm_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=apps.common.indexes.PostgresTrigramIndex(
                "phone", name="client_phone_trgm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=apps.common.indexes.PostgresTrigramIndex(
                "email", name="client_email_trgm_idx"
            ),
        ),
    ]
