# Generated by Django 5.1.2 on 2026-09-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_client_phone_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Клиент от…', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clients', to='clients.client'),
        ),
    ]
