# Generated by Django 5.1.2 on 2026-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_client_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="birth_place",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="registration_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                max_length=10,
            ),
        ),
    ]
