# Generated by Django 5.1.2 on 2026-09-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0016_client_birth_place_client_is_current_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="is_current",
        ),
    ]
