# Generated by Django 5.1.2 on 2025-12-28 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_alter_quote_insurance_company'),
        ('documents', '0006_open_notebook_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='web_view_link',
            field=models.URLField(blank=True, help_text='Ссылка для просмотра файла (legacy)', max_length=512),
        ),
        migrations.AlterField(
            model_name='knowledgenotebook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='KnowledgeSavedAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(help_text='Вопрос пользователя')),
                ('answer', models.TextField(help_text='Ответ Open Notebook')),
                ('citations', models.JSONField(blank=True, default=list, help_text='Источники ответа')),
                ('insurance_type', models.ForeignKey(blank=True, help_text='Вид страхования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_saved_answers', to='deals.insurancetype')),
                ('user', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_saved_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненный ответ',
                'verbose_name_plural': 'Сохраненные ответы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(help_text='ID сессии чата в Open Notebook', max_length=128)),
                ('insurance_type', models.ForeignKey(help_text='Вид страхования', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chat_sessions', to='deals.insurancetype')),
                ('user', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия чата Open Notebook',
                'verbose_name_plural': 'Сессии чата Open Notebook',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'insurance_type'), name='unique_knowledge_chat_session')],
            },
        ),
    ]
