# Generated by Django 5.1.2 on 2025-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_knowledgedocument_web_view_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenotebook',
            name='chat_session_id',
            field=models.CharField(blank=True, help_text='ID сессии чата Open Notebook', max_length=128),
        ),
    ]
