# Generated by Django 5.1.2 on 2025-12-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_knowledgenotebook_chat_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgesavedanswer',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='knowledgesavedanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='KnowledgeChatSession',
        ),
        migrations.DeleteModel(
            name='KnowledgeSavedAnswer',
        ),
    ]
