# Generated by Django 5.1.2 on 2025-12-28 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_knowledgesavedanswer_insurance_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenNotebookSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook_id', models.CharField(help_text='ID блокнота в Open Notebook', max_length=128, unique=True)),
                ('chat_session_id', models.CharField(help_text='ID сессии чата в Open Notebook', max_length=128)),
            ],
            options={
                'verbose_name': 'Сессия чата Open Notebook',
                'verbose_name_plural': 'Сессии чата Open Notebook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='knowledgenotebook',
            name='insurance_type',
        ),
        migrations.DeleteModel(
            name='KnowledgeDocument',
        ),
        migrations.DeleteModel(
            name='KnowledgeNotebook',
        ),
    ]
