# Generated by Django 5.1.2 on 2026-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_externaljob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaljob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("open_notebook_ask", "Вопрос Open Notebook"),
                    ("deal_drive_list", "Список файлов сделки в Drive"),
                    ("finance_statement_export", "Экспорт ведомости"),
                    ("financial_records_export", "Экспорт финансовых записей"),
                ],
                max_length=64,
            ),
        ),
    ]
