# Generated by Django 5.1.2 on 2025-11-11 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deals", "0005_alter_deal_expected_close_alter_deal_loss_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_name",
                    models.CharField(
                        default="Anonymous",
                        help_text="Author display name",
                        max_length=255,
                    ),
                ),
                ("body", models.TextField(help_text="Message text")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional user who posted the message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        help_text="Deal reference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat message",
                "verbose_name_plural": "Chat messages",
                "ordering": ["created_at"],
            },
        ),
    ]
