# Generated by Django 5.1.2 on 2026-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(help_text='Message body'),
        ),
    ]
