# Generated by Django 5.1.2 on 2025-11-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="pipeline",
        ),
        migrations.AddField(
            model_name="deal",
            name="stage_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name="DealStage",
        ),
        migrations.DeleteModel(
            name="Pipeline",
        ),
    ]
