# Generated by Django 5.1.2 on 2025-11-10 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_contact_client_remove_contact_owner_and_more'),
        ('deals', '0002_remove_deal_stage_remove_deal_pipeline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='primary_contact',
        ),
        migrations.AddField(
            model_name='deal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, help_text='Описание сделки'),
        ),
        migrations.AddField(
            model_name='deal',
            name='executor',
            field=models.ForeignKey(blank=True, help_text='Исполнитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Продавец', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='channel',
            field=models.CharField(blank=True, help_text='Канал продаж', max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_close',
            field=models.DateField(blank=True, help_text='Ожидаемая дата закрытия', null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='loss_reason',
            field=models.CharField(blank=True, help_text='Причина отказа', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='probability',
            field=models.PositiveIntegerField(default=0, help_text='Вероятность (0-100%)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source',
            field=models.CharField(blank=True, help_text='Источник', max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage_name',
            field=models.CharField(blank=True, help_text='Этап', max_length=120),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('won', 'Выиграна'), ('lost', 'Потеряна'), ('on_hold', 'В ожидании')], default='open', help_text='Статус сделки', max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(help_text='Название сделки', max_length=255),
        ),
    ]
