# Generated by Django 5.1.2 on 2025-11-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_alter_deal_options_remove_deal_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="probability",
        ),
    ]
