# Generated by Django 5.1.2 on 2025-11-11 00:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_options_deal_next_review_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='expected_close',
            field=models.DateField(blank=True, help_text='Плановая дата закрытия', null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='loss_reason',
            field=models.CharField(blank=True, help_text='Причина проигрыша', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Дата следующего контакта', null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Менеджер', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage_name',
            field=models.CharField(blank=True, help_text='Стадия', max_length=120),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('open', 'В работе'), ('won', 'Выиграна'), ('lost', 'Закрыта (проиграна)'), ('on_hold', 'На паузе')], default='open', help_text='Статус сделки', max_length=20),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.CharField(help_text='Страховая компания', max_length=255)),
                ('insurance_type', models.CharField(help_text='Тип страхования', max_length=120)),
                ('sum_insured', models.DecimalField(decimal_places=2, help_text='Страховая сумма', max_digits=14)),
                ('premium', models.DecimalField(decimal_places=2, help_text='Премия', max_digits=12)),
                ('deductible', models.CharField(blank=True, help_text='Франшиза', max_length=255)),
                ('comments', models.TextField(blank=True, help_text='Комментарий')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='deals.deal')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
