# Generated by Django 5.1.2 on 2025-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(default='open', help_text='Статус сделки (произвольный текст)', max_length=50),
        ),
    ]
