# Generated by Django 5.1.2 on 2025-11-13 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0007_alter_deal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="next_contact_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Дата следующего контакта (по-умолчанию - текущая дата)",
            ),
        ),
    ]
