# Generated by Django 5.1.2 on 2025-11-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_remove_probability"),
        ("deals", "0013_alter_quote_insurance_company"),
    ]

    operations = []
