# Generated by Django 5.1.2 on 2025-11-17 12:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0015_alter_quote_insurance_company_delete_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Название канала продаж", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Дополнительный комментарий"),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "Канал продаж",
                "verbose_name_plural": "Каналы продаж",
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="sales_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Канал продаж",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="deals.saleschannel",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["sales_channel"], name="deals_deal_sales_ch_idx"),
        ),
    ]
