# Generated by Django 5.1.2 on 2025-11-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0016_sales_channel_catalog"),
        ("policies", "0008_sales_channel_catalog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="channel",
        ),
    ]
