# Generated by Django 5.1.2 on 2025-11-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0011_quote_seller"),
        ("deals", "0018_remove_deal_deals_deal_sales_ch_idx_and_more"),
    ]

    operations = []
