# Generated by Django 5.x on 2026-02-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0022_alter_quote_insurance_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealViewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто добавил пользователя в наблюдатели",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal_viewer_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewer_links",
                        to="deals.deal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_viewer_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="visible_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователи с доступом только на просмотр",
                related_name="visible_deals",
                through="deals.DealViewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="dealviewer",
            constraint=models.UniqueConstraint(
                fields=("deal", "user"), name="unique_deal_viewer"
            ),
        ),
    ]

