# Generated by Django 5.x on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0023_normalize_deal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="official_dealer",
            field=models.BooleanField(
                default=False,
                help_text="Официальный дилер (да/нет)",
                verbose_name="Официальный дилер",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="gap",
            field=models.BooleanField(
                default=False,
                help_text="GAP (да/нет)",
                verbose_name="GAP",
            ),
        ),
    ]
