# Generated by Django 5.x on 2026-02-05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0023_deal_visible_users"),
        ("deals", "0025_alter_deal_status_dealpin"),
    ]

    operations = []

