# Generated by Django 5.1.2 on 2026-02-19 08:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0026_merge_20260205_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTimeTick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_start', models.DateTimeField()),
                ('seconds', models.PositiveSmallIntegerField(default=10)),
                ('source', models.CharField(default='deal_details_panel', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_ticks', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_time_ticks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bucket_start', '-created_at'],
                'indexes': [models.Index(fields=['deal', 'user'], name='deals_dealt_deal_id_09a6b8_idx'), models.Index(fields=['user', 'created_at'], name='deals_dealt_user_id_aa5ca4_idx'), models.Index(fields=['deal', 'created_at'], name='deals_dealt_deal_id_d91414_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'bucket_start'), name='deals_unique_user_bucket_tick')],
            },
        ),
    ]
