# Generated by Django 5.1.2 on 2026-02-21 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0027_dealtimetick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='next_contact_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Дата следующего контакта (по-умолчанию - текущая дата)', null=True),
        ),
    ]
