# Generated by Django 5.1.2 on 2026-02-21 19:05

import django.utils.timezone
from django.db import migrations, models


def fill_null_next_contact_dates(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    Deal.objects.filter(next_contact_date__isnull=True).update(
        next_contact_date=django.utils.timezone.localdate()
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0028_alter_deal_next_contact_date"),
    ]

    operations = [
        migrations.RunPython(fill_null_next_contact_dates, noop_reverse),
        migrations.AlterField(
            model_name="deal",
            name="next_contact_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Дата следующего контакта (по-умолчанию - текущая дата)",
            ),
        ),
    ]
