# Generated by Django 5.1.2 on 2026-06-16 21:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0031_populate_insurance_type_descriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("manual_expected_close", "Дата страхования вручную"),
                            ("manual_next_contact", "Следующий контакт вручную"),
                            ("payment_due", "Очередной платеж"),
                            ("policy_expiration", "Окончание полиса"),
                            ("deal_updated", "Сделка изменена"),
                            ("task_created", "Задача создана"),
                            ("task_completed", "Задача завершена"),
                            ("policy_created", "Полис создан"),
                            ("quote_created", "Расчет создан"),
                            ("file_uploaded", "Файл загружен"),
                        ],
                        max_length=64,
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("source_type", models.CharField(blank=True, max_length=64)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие сделки",
                "verbose_name_plural": "События сделок",
                "ordering": ["-event_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["deal", "-event_date", "-created_at"],
                        name="deals_deale_deal_id_e8cfba_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="deals_deale_event_t_fb52a6_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="deals_deale_source__48cafa_idx",
                    ),
                ],
            },
        ),
    ]
