# Generated by Django 5.1.2 on 2026-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0032_dealevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealevent',
            name='event_type',
            field=models.CharField(choices=[('manual', 'Ручное событие'), ('manual_expected_close', 'Дата страхования вручную'), ('manual_next_contact', 'Следующий контакт вручную'), ('payment_due', 'Очередной платеж'), ('policy_expiration', 'Окончание полиса'), ('deal_updated', 'Сделка изменена'), ('task_created', 'Задача создана'), ('task_completed', 'Задача завершена'), ('policy_created', 'Полис создан'), ('quote_created', 'Расчет создан'), ('file_uploaded', 'Файл загружен')], max_length=64),
        ),
    ]
