# Generated by Django 5.1.2 on 2026-06-21 11:20

from django.db import migrations

LEGACY_MANUAL_DEADLINE_TITLE = "Крайний срок из старых данных"
LEGACY_MANUAL_DEADLINE_ORIGIN = "legacy_manual_expected_close"


def materialize_legacy_manual_expected_close_events(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    DealEvent = apps.get_model("deals", "DealEvent")

    legacy_deals = (
        Deal.objects.filter(manual_expected_close__isnull=False)
        .only("id", "manual_expected_close")
        .iterator()
    )
    events_to_create = []

    for deal in legacy_deals:
        event_exists = DealEvent.objects.filter(
            deal_id=deal.id,
            event_type="manual_expected_close",
            event_date=deal.manual_expected_close,
        ).exists()
        if event_exists:
            continue

        events_to_create.append(
            DealEvent(
                deal_id=deal.id,
                event_type="manual_expected_close",
                event_date=deal.manual_expected_close,
                title=LEGACY_MANUAL_DEADLINE_TITLE,
                description="",
                source_type="deal",
                source_id=str(deal.id),
                actor_id=None,
                metadata={"origin": LEGACY_MANUAL_DEADLINE_ORIGIN},
            )
        )

    DealEvent.objects.bulk_create(events_to_create, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0034_manual_expected_close_deadline"),
    ]

    operations = [
        migrations.RunPython(
            materialize_legacy_manual_expected_close_events,
            migrations.RunPython.noop,
        ),
    ]
