# Generated by Django 5.1.2 on 2026-06-22

from django.db import migrations
from django.db.models import Q


def _earliest(*values):
    candidates = [value for value in values if value is not None]
    return min(candidates) if candidates else None


def convert_manual_events_to_deadlines(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    DealEvent = apps.get_model("deals", "DealEvent")
    Payment = apps.get_model("finances", "Payment")
    Policy = apps.get_model("policies", "Policy")

    manual_events = DealEvent.objects.filter(event_type="manual")
    affected_deal_ids = list(
        manual_events.order_by().values_list("deal_id", flat=True).distinct()
    )

    for event in manual_events.iterator():
        DealEvent.objects.filter(pk=event.pk).update(
            event_type="manual_expected_close",
            source_type="deal",
            source_id=str(event.deal_id),
            description="",
        )

    for deal_id in affected_deal_ids:
        manual_deadline = (
            DealEvent.objects.filter(
                deal_id=deal_id,
                event_type="manual_expected_close",
                event_date__isnull=False,
            )
            .order_by("event_date", "created_at")
            .values_list("event_date", flat=True)
            .first()
        )
        policy_deadline = (
            Policy.objects.filter(
                deal_id=deal_id,
                deleted_at__isnull=True,
                end_date__isnull=False,
            )
            .filter(Q(is_renewed=False) | Q(is_renewed__isnull=True))
            .order_by("end_date")
            .values_list("end_date", flat=True)
            .first()
        )
        payment_deadline = (
            Payment.objects.filter(
                Q(deal_id=deal_id) | Q(policy__deal_id=deal_id),
                deleted_at__isnull=True,
                actual_date__isnull=True,
                scheduled_date__isnull=False,
            )
            .order_by("scheduled_date")
            .values_list("scheduled_date", flat=True)
            .first()
        )
        Deal.objects.filter(pk=deal_id).update(
            manual_expected_close=manual_deadline,
            expected_close=_earliest(
                manual_deadline, policy_deadline, payment_deadline
            ),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0035_materialize_legacy_manual_expected_close_events"),
        ("finances", "0011_statement_unique_normalized_name"),
        ("policies", "0020_remove_policy_renewed_by_policy_is_renewed"),
    ]

    operations = [
        migrations.RunPython(
            convert_manual_events_to_deadlines,
            migrations.RunPython.noop,
        ),
    ]
