# Generated by Django 5.1.2 on 2026-07-23 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0037_deal_deal_title_trgm_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='calculation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Подтверждённые данные для расчёта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='calculation_source_file_ids',
            field=models.JSONField(blank=True, default=list, help_text='ID файлов Google Drive, использованных для расчёта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='calculation_source_text',
            field=models.TextField(blank=True, help_text='Текстовый источник данных для расчёта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='calculation_type',
            field=models.CharField(blank=True, help_text='Тип расчёта для формализованных данных', max_length=32),
        ),
        migrations.AddField(
            model_name='deal',
            name='calculation_updated_at',
            field=models.DateTimeField(blank=True, help_text='Дата подтверждения данных расчёта', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='calculation_updated_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, подтвердивший данные расчёта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_deal_calculations', to=settings.AUTH_USER_MODEL),
        ),
    ]
