# Generated by Django 5.1.2 on 2026-08-08 16:04

import apps.common.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0014_client_client_phone_trgm_idx_and_more"),
        ("deals", "0038_deal_calculation_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deal",
            index=apps.common.indexes.PostgresTrigramIndex(
                "description", name="deal_descr_trgm_idx"
            ),
        ),
    ]
