# Generated by Django 5.1.2 on 2026-08-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0039_deal_deal_descr_trgm_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealTimeTick',
        ),
    ]
