# Generated by Django 5.1.2 on 2026-08-22 15:27

import apps.deals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0040_remove_dealtimetick'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='logo',
            field=models.FileField(blank=True, help_text='Логотип в формате PNG, WebP или SVG размером до 2 МБ', upload_to='insurance_company_logos/', validators=[apps.deals.validators.validate_insurance_company_logo]),
        ),
    ]
