# Generated by Django 5.1.2 on 2026-09-22 09:00

import apps.deals.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0041_insurancecompany_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Название банка', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о банке')),
                ('logo', models.FileField(blank=True, help_text='Логотип в формате PNG, WebP или SVG размером до 2 МБ', upload_to='bank_logos/', validators=[apps.deals.validators.validate_insurance_company_logo])),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
            },
        ),
    ]
