# Generated by Django 5.1.2 on 2026-09-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0042_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='sum_insured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Страховая сумма', max_digits=14, null=True),
        ),
    ]
