# Generated by Django 5.1.2 on 2026-09-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0043_alter_quote_sum_insured"),
        ("insurance_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="insurance_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="insurance_requests.insurancerequest",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="request_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="insurance_requests.requestvariant",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="request_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="insurance_requests.requestversion",
            ),
        ),
    ]
