# Generated by Django 5.1.2 on 2026-02-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0026_merge_20260205_1200'),
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox', to='deals.deal'),
        ),
        migrations.CreateModel(
            name='MailboxProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=512)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('sender', models.CharField(blank=True, max_length=512)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to='mailboxes.mailbox')),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['mailbox', 'message_id'], name='mailboxes_m_mailbox_225690_idx')],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'uid'), name='uniq_mailbox_uid')],
            },
        ),
    ]
